### ISSUE TITLE
Row.mkString() and Row.equals() needs to handle larger numbers better

### ISSUE THREAD

**Issue by billreed63** [EclairJS/eclairjs-nashorn#11]
Also, I happened to notice that really large numbers get stored in scientific notation and are never properly converted back into decimal form thus are never queried back out of DataFrame/Row in proper form (as in Row.mkString()).

For instance if I have something like 'networth' as a field in a row that is a Double and a typical value is something like 300000000.11, it is stored as 3.0000000011E8 and never converted back to 300000000.11 in calls like Row.mkString() and Row.equals(), etc.

**Comment by jtbarbetta** [comment]
I verified this is now fixed.  Thank you Bill!
