### ISSUE TITLE
javascript sample spark_tc.js is 25x slower than java version

### ISSUE THREAD

**Issue by pberkland** [EclairJS/eclairjs-nashorn#112]
the spark_tc example takes 25 min to run vs a minute and a half on java.  This is running with the same data, and with minimal javascript logic.

This example causes pair function to be called many times (100000?), so the issue is probably the time going from java into js function, and back out.
It is possible a new Nashorn engine is being created every time, although it is using a singleton

**Comment by billreed63** [comment]
@pberkland  Where is the Java example?

**Comment by pberkland** [comment]
(org.apache.spark.examples.)JavaTC
from the spark install dir, run: 
 ./bin/run-example JavaTC

**Comment by pberkland** [comment]
is the function being compiled every invocation?
        e.eval(this.func);
        Invocable invocable = (Invocable) e;
maybe it could be cached

**Comment by billreed63** [comment]
Turns out we don't have a performance issue, the root cause for the difference between the Java version and the JavaScript version is the random number generation.

the key bit of code from the example is the do/while loop:

```
do {
            oldCount = nextCount;
            // Perform the join, obtaining an RDD of (y, (z, x)) pairs,
            // then project the result to obtain the new (x, z) paths.
            JavaPairRDD<Integer, Tuple2<Integer, Integer>> j = tc.join(edges);
            JavaPairRDD<Integer, Integer> x =  j.mapToPair(ProjectFn.INSTANCE);
            JavaPairRDD<Integer, Integer> y = tc.union(x);
            //tc = x.distinct().cache();
            tc = y.distinct().cache();
            nextCount = tc.count();
            System.out.println("oldCount= " + oldCount + " nextCount=" + nextCount +  " loopCount=" + ++loopCount);
        } while (nextCount != oldCount);
```

On the Java version I consistently see, TC has 6254 edges. loopCount=12 at a time of about 40 seconds. On JavaScript consistently above 6254 edges, and loopCount > 12. If we limit the number of times that the JavaScript version loops to 12 iteration of the loop the JavaScript code runs about 40 seconds.

**Comment by billreed63** [comment]
To verify that the root cause of the performance difference is the random number generation, I replaced the JavaScript code

```
function random(max) {
    var x = Math.floor(Math.random() * max);
    return parseInt(x);
}
```

With that Java Random generator

```
var rand = new java.util.Random(42);
```

Now I consistently get 

```
oldCount= 6091 nextCount=6091 loopCount=12
TC has 6091 edges.
difference = 0 day/s 0 hour/s 0 minute/s 45 second/s 
```
