### ISSUE TITLE
Do we need to namespace and or a RequireJS type loader

### ISSUE THREAD

**Issue by billreed63** [EclairJS/eclairjs-nashorn#12]
Currently we do not have class name collisions, but do we need to "future proof" our JavaScript code by using namespace for the spark package names For example `DataFrame = sql.DataFrame` The use of a loader like RequireJS would alleviate this issues because of src directory structure 

```
requirejs(["sql/DataFrame"], function(DataFrame) {
    DataFrame.apply(...);
});
```

Currently we load all JavaScript files when we create the Nashorn engine, so the issue with a RequireJS loader is that of LAMDA functions scope. The LAMDA functions running on the slave will create a new Nashorn engine, if the `requirejs([....])` is not done inside the LAMDA function the necessary JavaScript files will not be loaded in the Nashorn engine on the slave. This is the reason for the current implementation of loading all JavaScript files at Nashorn engine creation.

**Comment by billreed63** [comment]
Here are some requirements/limitations that need to be addressed:
- All scripts loaded in the master should be automatically loaded in the slaves.  When we spin up a new nashorn engine we execute `NashornEngineSingleton.loadSparkJS()` this currently loads all of our "wrapper" JavaScript files. We spin up a new nashorn engine the master and slaves. 
- Do not require the user to repeat loading of JavaScript files in the LAMDA functions, if the user "requires" a JS file in the global scope we need to remember that load and automatically load it on the slaves when the nashorn engine is created.
- Distributions of users JavaScript files to the slaves, when the user adds custom code  `require("./myUtils.js")` we need to ensure that that code is distributed to the salves by `SparkContext.addFile()` and then add those files to the nashorn engine with `load(SparkFiles.get("myUtils.js"))`

**Comment by jtbarbetta** [comment]
I'm going to test a bit around some of the options we have for crating the ScriptContext for each instance of the javax.script.ScriptEngine we're creating.  See (I think our answer is here): https://wiki.openjdk.java.net/display/Nashorn/Nashorn+jsr223+engine+notes.

**Comment by jtbarbetta** [comment]
So I've been experimenting with using the module loader I found (https://github.com/nodyn/jvm-npm) that we talked about and it seems to be working.

I have the following example working:
(In hello.js):
module.exports = function sayHello(numTimes) {
  var num = numTimes || 2;
  for (var i = 0; i < num; i++) {
    print("Hello World");
  }
};
(In simple.js)
var SparkContext = require('./src/main/resources/SparkContext');
var hello = require('./examples/jvm-npm/hello');
print('typeof hello: ' + typeof hello);
var sparkContext = new SparkContext("local[*]", "Simple jvm-npm");
var list = sparkContext.parallelize([1,10,20,30,40]);
hello(list.count());
sparkContext.stop();

(From command line eclairjs-nashorn root running our script):
bin/eclairjs.sh examples/jvm-npm/simple.js
(Yields what I expect):
typeof hello: function
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/02/10 17:51:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/02/10 17:51:49 INFO Remoting: Starting remoting
16/02/10 17:51:49 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.4.126:56333]
Hello World  
Hello World
Hello World
Hello World
Hello World

This proves:
1) User can 'require' custom code (w/relative path)
2) Dependencies (as long as required by modules that use them e.g. SparkContext 'requires' SparkConf) are resolved (I tried it without require of SparkConf in SparkContext and it did complain as expected)
3) We should only have to 'load' jvm-npm.js in SparkBootstrap when all is said and done

I still want to test a bit with:
1) Paths other than relative path (I don't like "var SparkContext = require('./src/main/resources/SparkContext');" in simple.js)
2) Test on Spark cluster to make sure 'requires' get to worker nodes with lambda functions.
3) Converting all of our wordcount example to this mechanism 

If we decide to go this route what would need to be done is (but not limited to):
1) Export all of our Spark wrapper code as modules
2) Make sure dependencies are 'required' properly in our code
3) Converting all of our tests/examples over to 'require' what they need

**Comment by billreed63** [comment]
I would suggest that the word_count example is too simplistic, I would suggest using examples/mllib/linearregressiontest.js

We will also might need to change the code in Utils.java method javaTojs

```
/*
         * Any object that belongs to Spark we will wrapper it with a JavaScript object
         * If we don't have a JavaScript wrapper for it then we will catch the
         * exception and just use the wrapObject method.
         */
        if ((packageName != null) && (packageName.indexOf("org.apache.spark") > -1)) {
            logger.debug("spark object");
            String className = o.getClass().getSimpleName();
            try {
                Invocable invocable = (Invocable) engine;
                if (className.endsWith("$")) {
                    //anonymous class
                    logger.debug("getSuperClass for " + className);
                    className = o.getClass().getSuperclass().getSimpleName();
                }
                if ( className.equals("JavaRDD")) {
                    /*
                     * Map JavaRDD to RDD for JavaScript
                     */
                    className = "RDD"; //o.getClass().getSimpleName();
                }
                logger.debug("create " + className);
                Object params[] = {className, o};
                Object parm = invocable.invokeFunction("createJavaWrapperObject", params);
                logger.debug(parm);
                return parm;
            } catch (Exception e) {
                logger.warn(className + " convertion error, will just wrapObject " + e);
                logger.debug(className + " javaToJs instanceof  " + o.getClass());
                return wrapObject(o);
            }

        } 
```

and Utils.js to include a `require()`

```
function createJavaWrapperObject(className, obj) {
      return eval("new " + className + "(obj)");
  };
```

**Comment by jtbarbetta** [comment]
We have started a wiki page for proposals for this issue since it is an architectural design point.  For further discussion please refer to: https://github.com/EclairJS/eclairjs-nashorn/wiki/Proposals-for-module-loader-for-lambdas

**Comment by Brian-P-Burns** [comment]
Closing this issue, since we have the wiki page for discussion and this is targeted for Milestone 0.4

**Comment by jtbarbetta** [comment]
This was rolled into master for the .4 milestone release.  We can finally close it for good.
