### ISSUE TITLE
Implement RDD API to 1.6

### ISSUE THREAD

**Issue by billreed63** [EclairJS/eclairjs-nashorn#13]
Implement RDD API to spark 1.5.1

**Comment by jtbarbetta** [comment]
Implemented rest of RDD a-z and updated to 1.5.1 with commit 98cbd17.  

Still have to finish unit tests and address remaining issues with the following:
checkpointData: 
- skipping - returns scala specific construct
- not in generated code

clearDependencies
- skipping - seems to be Java specific
- not in generated code

collect(scala.PartialFunction<T,U> f, scala.reflect.ClassTag<U> evidence$31)
- implemented as collectwithF

compute
- skipping - seems to be Java specific
- not in generated code

countByValue
- needs to be implemented
- not sure about return Map

dependencies
- needs to be implemented
- not sure about return Seq

doubleRDDToDoubleRDDFunction
    skipping - seems to be Java specific
    in generated code but not in prototype

firstParent
- skipping - seems to be Java specific
- not in generated code

getDependencies
- skipping - seems to be Scala specific
- not in generated code

getPartitions
- skipping - seems to be Scala specific
- not in generated code

getPreferredLocations
- skipping - seems to be Scala specific
- not in generated code

groupBy
- Partitioner needs to be implemented

intersection
- Partitioner needs to be implemented

iterator
- skipping - doesn’t make sense for Javascript

mapPartitionsWithContext
- skipping - when you remove params that are scala specific it is same as mapPartitions
- not in generated code

preferredLocations
- needs to be implemented
- not sure about return Seq

rddToAsyncRDDActions, rddToOrderedRDDFunctions, rddToPairRDDFunctions, rddToSequenceFileRDDFunctions
- skipping - they don’t seem to make sense for Javascript

saveAsTextFilewithCodec
- need to add codec param to saveAsTextFile to implement
- not sure how to handle codec

scope
- skipping - seems to be Scala specific
- not in generated code

toJavaRDD
- skipping - makes no sense for JavaScript

toLocalIterator
- skipping - Imakes no sense for JavaScript

**Comment by jtbarbetta** [comment]
Implementation and tests are done for just about everything that makes sense for JavaScript for RDD to get up to par with Spark 1.5.1.  There are a few that need other classes implemented for them which are covered under separate issues (#28,#29).
