### ISSUE TITLE
change CoreTest so user can run/debug individual test from the suite

### ISSUE THREAD

**Issue by billreed63** [EclairJS/eclairjs-nashorn#142]
From IntellJ or eclipse I can run/debug an individual test from SqlTest by selecting the test and run/debug it. For example I can run SqlTest.dataframeWithColumnTest I am unable to select and individual test from CoreTest, I have to run all the test

**Comment by pberkland** [comment]
fixed via commit 9bb7b1b6fecedf3d033fb3d795c08f39c8d8eae8

When you want to run an individual test, you will need to add an empty java method
with the same name as the javascript function to to the java test class, i.e.
        @Test
        public void version()  {}
will allow the test method 'version' to be run/debugged individualy.
