### ISSUE TITLE
returned wrappers for subclasses are incorrect

### ISSUE THREAD

**Issue by pberkland** [EclairJS/eclairjs-nashorn#172]
PairRDD is a subclass of RDD (and PairDStream is subclass of DStream).  Since the subclasses do not implement the functions of the base class, the wrong wrapper class (the base class wrapper) will be created when calling one of the functions on the base class.
For instance,  rdd.mapToPair( ...).setName().sortByKey() would fail because setName (a base class function) would return the RDD wrapper class which does not have the sorByKey() function.

Instead of explicitly creating the wrapper class instances,  the Serialize.javaSparkObject  should be used to create correct wrapper class based on what the returned java object is.

**Comment by pberkland** [comment]
Still a problem for PairDStream

**Comment by billreed63** [comment]
What is the problem?

**Comment by pberkland** [comment]
No problem with anything you did, I just need to make the same changes to PairDStream that you did for PairRDD

**Comment by pberkland** [comment]
fixed PairDStream via commit 8157b705e70627d54cd62b6e03a3d588dd98dcca
