### ISSUE TITLE
Node code generation creating {type} rather than the actual return type

### ISSUE THREAD

**Issue by doronrosenberg** [EclairJS/eclairjs-nashorn#222]
For example ml/recommendation/ALS - it shows @return {type} rather than the actual type its returning.

**Comment by doronrosenberg** [comment]
Another thing I noticed is that it also generated {StructType} rather than the fully qualified name ({module:eclairjs/sql/types.StructType})

**Comment by pberkland** [comment]
these were fixed by commit 08d1846b40c87d67aefbf66f41f3ddd7ab249535, but the generated node code was not fully uploaded, uploading again, watch for code with new timestamp
