### ISSUE TITLE
Implement sql.UserDefinedFunction

### ISSUE THREAD

**Issue by billreed63** [EclairJS/eclairjs-nashorn#262]

**Comment by Brian-P-Burns** [comment]
Here is what a udf would look like in scala. The existing data frame has separate day, month, year, hour, minute and second fields.  You can create a udf to combine those fields into a single timestamp field.

`import org.apache.spark.sql.functions.udf

//create UDF function by calling udf wrapper.
val timeFunc = udf(
(day: String, month: String, year: String, hour: String, minute: String, second: String) => {
    new java.sql.Timestamp(Integer.parseInt(year), 
        Integer.parseInt(month), 
        Integer.parseInt(day), 
        Integer.parseInt(hour), Integer.parseInt(minute), Integer.parseInt(second), 0)
})

val df2 = df.withColumn("timestamp", timeFunc($"day", $"month", $"year", $"hour", $"minute", $"second"))`

**Comment by billreed63** [comment]
@bpburns  commit 2bc24ea contains a UDF6 implementation you should be able to use for the example above the JavaScript code would look like:

```
var SqlTimestamp = require(EclairJS_Globals.NAMESPACE + '/sql/SqlTimestamp');
    var fields = [];
    fields.push(DataTypes.createStructField("day", DataTypes.StringType, true));
    fields.push(DataTypes.createStructField("month", DataTypes.StringType, true));
    fields.push(DataTypes.createStructField("year", DataTypes.StringType, true));
    fields.push(DataTypes.createStructField("hour", DataTypes.StringType, true));
    fields.push(DataTypes.createStructField("minute", DataTypes.StringType, true));
    fields.push(DataTypes.createStructField("second", DataTypes.StringType, true));
    var schema = DataTypes.createStructType(fields);
    var df = sqlContext.createDataFrame([["26", "6", "1999", "9", "12", "30"]], schema);
    df.registerTempTable("mytable");

    sqlContext.udf().register("udfTest", function(day, month, year, hour, minute, second, SqlTimestamp) {
        var ts = new SqlTimestamp(new Date(year, month-1, day, hour, minute, second));
        return ts;
    }, DataTypes.TimestampType, [SqlTimestamp]);

    var result = sqlContext.sql("SELECT *, udfTest(mytable.day, mytable.month, mytable.year, mytable.hour, mytable.minute, mytable.second) as timestamp FROM mytable").collect();

    return JSON.stringify(result);
```
