### ISSUE TITLE
Integer to Double Conversion Errors

### ISSUE THREAD

**Issue by doronrosenberg** [EclairJS/eclairjs-nashorn#275]
@bpburns 

See EclairJS/eclairjs-node/issues/102

Basically a schema defines `DataTypes.DoubleType` but javascript converts `1.0` to `1` and you get cast errors.

**Comment by billreed63** [comment]
@doronrosenberg 
Can you provide example code?

**Comment by doronrosenberg** [comment]
This is actually solved in 0.5, I was testing using an older jar.
