### ISSUE TITLE
DataFrame Numeric Conversion Issues

### ISSUE THREAD

**Issue by jtbarbetta** [EclairJS/eclairjs-nashorn#3]
When trying to create a Dataframe with Row schema that includes any of the numeric DataTypes the conversion between spark type and the way Java stores the numeric data is not being done correctly.  

Specifically if the Row schema uses any of the following:
DataTypes.prototype.DecimalType
DataTypes.prototype.FloatType

They are converted to and stored as Java type of Double.  For instance, if you have var floatNum = 12.4 it gets stored as double even if schema usesDataTypes.prototype.FloatType for that cell.  Is seems that unless you specify 12.4f Java assumes a double and we have no way to pass the 'f' from Node side along).  Then upon trying to select an entire Row or get data of that type at a certain index (e.g. Row.getFloat()) a ClassCastException is thrown because it is quieries back out of the DataFrame as a Double e.g.
15/11/24 16:01:59 [ERROR] o.a.s.e.Executor - Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
    at scala.runtime.BoxesRunTime.unboxToFloat(BoxesRunTime.java:114)
    at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getFloat(rows.scala:42)
    at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getFloat(rows.scala:220)
    at org.apache.spark.sql.catalyst.CatalystTypeConverters$FloatConverter$.toScalaImpl(CatalystTypeConverters.scala:371)

The same holds true for the following getting treated as Integer by Java:
DataTypes.prototype.ShortType
DataTypes.prototype.LongType

Also, I happened to notice that really large numbers get stored in scientific notation and are never properly converted back into decimal form thus are never queried back out of DataFrame/Row in proper form (as in Row.mkString()).

For instance if I have something like 'networth' as a field in a row that is a Double and a typical value is something like 300000000.11, it is stored as 3.0000000011E8 and never converted back to 300000000.11 in calls like Row.mkString() and Row.equals(), etc.

**Comment by billreed63** [comment]
I removed the DataTypes that are not mapped JavaScript types https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/nashorn/api.html  So the supported types are 
/**
- Gets the BooleanType object.
- @static
  _/
  DataTypes.BooleanType = org.apache.spark.sql.types.DataTypes.BooleanType;
  /_*
- Gets the DateType object.
- @static
  _/
  DataTypes.DateType = org.apache.spark.sql.types.DataTypes.DateType;
  /_*
- Gets the DoubleType object.
- @static
  _/
  DataTypes.DoubleType = org.apache.spark.sql.types.DataTypes.DoubleType;
  /_
- NOTE:
- Nashorn interprets numbers as java.lang.Double, java.lang.Long, or java.lang.Integer objects, depending on the computation performed. 
- You can use the Number() function to force a number to be a Double object
- https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/nashorn/api.html
  _/
  /_*
- Gets the DoubleType object. Note: JavaScript float types are mapped to DoubleTypes in Spark,
- The user should use the DoubleType for all float processing
- @static
  _/
  DataTypes.FloatType = org.apache.spark.sql.types.DataTypes.DoubleType;
  /_\* Gets the IntegerType object.
- @static
  _/
  DataTypes.IntegerType = org.apache.spark.sql.types.DataTypes.IntegerType;
  /_*
- Gets the StringType object.
- @static
  _/
  DataTypes.StringType = org.apache.spark.sql.types.DataTypes.StringType;
  /_*
- Gets the TimestampType object.
- @static
  */
  DataTypes.TimestampType = org.apache.spark.sql.types.DataTypes.TimestampType;

/*
- NOTE:
- the following types are not applicable to JavaScript so we are not implement them
  */
  I update Row methods and removed the unsupported types.

I will open a separate issue to address the Row.mkString() and Row.equals() issues

**Comment by billreed63** [comment]
I opened #11 for the Row.mkString and Row.equals()

**Comment by jtbarbetta** [comment]
I synched up Node side of Row with Nashorn side such that DataTypes that we support are same on each side and then verified numeric conversion issues for what we are supporting are fixed.  Thank you Bill!
