### ISSUE TITLE
investigate what needs to be be done to move to spark 1.6

### ISSUE THREAD

**Issue by pberkland** [EclairJS/eclairjs-nashorn#30]
- how many new APIs are there?
- how many changed APIs are there?
- does spark kernel change to 1.6?

**Comment by pberkland** [comment]
1.6 (over 1.5.1) difference summary
-  122 new api functions
- 680 total new functions including methods which are probably internal/impl
- no functions removed
- a large number of "Experimental" tags removed from JSDoc
- minor JSDoc differences

**Comment by pberkland** [comment]
The Spark Kernel works with 1.6

**Comment by billreed63** [comment]
I was able to compile and run our test case on Spark 1.6.0. But when I attempted to run our code in Jupyter notebooks the kernel kept crashing.

**Comment by billreed63** [comment]
I found my issue, I had a bad line in my kernel.json file.

So the steps that I used to successfully run in a Jupyter notebook

1) Build Toree with Spark 1.6.0 

```
export APACHE_SPARK_VERSION=1.6.0
make dist
sbt publishM2
```

2) Build EclairJS-nashorn 

```
mvn package -Pnotebook
```

3) update kernel.json

```
{
  "display_name": "Spark 1.6.0 (EclairJS)",
  "language": "javascript",
  "argv": [
    "/Users/billreed/eclairjs_dev/incubator-toree/dist/spark-kernel/bin/spark-kernel",
    "--interpreter-plugin",
    "eclair:org.eclairjs.nashorn.JavascriptInterpreter",
    "--default-interpreter",
    "eclair",
    "--nosparkcontext",
    "--profile",
    "{connection_file}"
  ],
  "env": {
    "SPARK_OPTS": "--jars file:/Users/billreed/eclairjs_dev/eclairjs-nashorn/target/eclairjs-nashorn-0.1.jar",
    "SPARK_HOME": "/Users/billreed/Downloads/spark-1.6.0-bin-hadoop2.6/"
  },
  "codemirror_mode": "scala"
}
```

4) start notebook

```
ipython notebook
```

**Comment by pberkland** [comment]
1.6 spark is now implemented
