### ISSUE TITLE
Issue using an external js library.

### ISSUE THREAD

**Issue by lrodriguez2002cu** [EclairJS/eclairjs-nashorn#315]
Hi, I have the following issue while trying to use an external js library in a script:

Based on the wordcount example:

```
function runSimple(sparkContext) {

    var Tuple2 = require('eclairjs/Tuple2');

    var file = ((typeof arguments !== "undefined") && (arguments.length > 1)) ? arguments[1] : "samplefile.txt";

   var rdd = sparkContext.textFile(file).cache();

   var turf = require("./lib/turf.js");

    var rdd2 = rdd.flatMap(function (sentence) {
        var split = sentence.split(" ");
        return split;
    });

    print("rdd2 count:" + rdd2.count());
    print("rdd2 collect:" + rdd2.collect());

    var rdd3 = rdd2.filter(function (word) {
        print((typeof  word) + ':' + word);
        return word.trim().length > 0;
    });

    var rdd4 = rdd3.mapToPair(function (word, Tuple2) {
        return new Tuple2(word, 1);
    }, [Tuple2]);

    var rdd5 = rdd4.reduceByKey(function (a, b) {
        return a + b;
    });

    var rdd6 = rdd5.mapToPair(function (tuple, Tuple2) {
        return new Tuple2(tuple._2() + 0.0, tuple._1());
    }, [Tuple2])

    var rdd7 = rdd6.sortByKey(false);
    return rdd7.take(10);

}

```

The sample file used in this case only contains (ignore the begin file and end file):
--begin file--
a b
--end file, no new line after b, just a, b--

The printed values of evaluating the function runSimple():

rdd2 count:3
rdd2 collect:a,b,[object Object]
string:a
string:b
object:[object Object]

The expected count would be in this case 2, and only a and b should be printed:  

If the library turf.min.js is not loaded (or even moved down to the end of the script), the problem goes away, which indicates it has some kind of interaction.  The extra object aparently corresponds to new lines and end of file, as adding new lines increases the counter in the same amount.

The library I am including is [Turf.js](http://turfjs.org/).

Any advice for solving this issue? 
Thanks in advance.

**Comment by doronrosenberg** [comment]
@jtbarbetta module loading question

**Comment by billreed63** [comment]
Turf.js is for node.js or browsers, Eclairjs-nashorn runs on the Spark driver and workers and is meant for batch type operation. If you are attempting to write a node spark interactive  application  that uses Turf.js you need to use [EclairJS-node](https://github.com/EclairJS/eclairjs-node). EcairJS-node will allow you to use Turf.js

**Comment by jtbarbetta** [comment]
Thank you for answering this Bill!

**Comment by lrodriguez2002cu** [comment]
Thank you very much for your answers, I was hoping to be able to use Turf for using the  geo-spatial analysis capabilities. Indeed I have tested a simple example running on top of eclairjs-nashorn, using the browser version and seems to work properly. It is now clear for me that it is introducing some other issues due to the fact that is for running on the browser o on node.js.  Thanks again!
