### ISSUE TITLE
Cannot use take() on a DataFrame created by a sort

### ISSUE THREAD

**Issue by doronrosenberg** [EclairJS/eclairjs-nashorn#36]
```
var jsc = new SparkContext("local[*]", "foo");
var sqlContext = new SQLContext(jsc);
var rdd1 = jsc.textFile("/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/test/data/people.txt");
var sqlStructField1 = DataTypes.createStructField("name", org.apache.spark.sql.types.DataTypes.StringType, true);
var sqlStructField2 = DataTypes.createStructField("age", org.apache.spark.sql.types.DataTypes.IntegerType, true);
var sqlStructField3 = DataTypes.createStructField("expense", org.apache.spark.sql.types.DataTypes.IntegerType, true);

var rdd2 = rdd1.map(function (line) {
    var parts = line.split(",");
    return person = {
      name: parts[0],
      age: parseInt(parts[1].trim()),
      expense: parseInt(parts[2].trim())
    };
  });
var sqlStructType1 = DataTypes.createStructType([sqlStructField1,sqlStructField2,sqlStructField3,sqlStructField4,sqlStructField5]);
var rdd3 = rdd2.map(function (person){
    return RowFactory.create([person.name, person.age, person.expense, person.hasJob, person.isOld]);
  });
var dataFrame1 = sqlContext.createDataFrame(rdd3, sqlStructType1);

var column1 = dataFrame1.col("age");
var column2 = column1.asc();
var dataFrame2 = dataFrame1.sort(column2);
JSON.stringify(dataFrame2.take(10));
```

Error is: 

Name: java.lang.RuntimeException
Message: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1.0 in stage 4.0 (TID 9) had a not serializable result: jdk.nashorn.internal.runtime.Undefined
Serialization stack:
    - object not serializable (class: jdk.nashorn.internal.runtime.Undefined, value: undefined)
    - element of array (index: 3)
    - array (class [Ljava.lang.Object;, size 5)
    - field (class: org.apache.spark.sql.catalyst.expressions.GenericInternalRow, name: values, type: class [Ljava.lang.Object;)
    - object (class org.apache.spark.sql.catalyst.expressions.GenericInternalRow, [Justin,19,3,undefined,undefined])
    - writeObject data (class: java.util.PriorityQueue)
    - object (class java.util.PriorityQueue, [[Justin,19,3,undefined,undefined]])
    - field (class: org.apache.spark.util.BoundedPriorityQueue, name: underlying, type: class java.util.PriorityQueue)
    - object (class org.apache.spark.util.BoundedPriorityQueue, BoundedPriorityQueue([Justin,19,3,undefined,undefined]))
    - field (class: scala.Some, name: x, type: class java.lang.Object)
    - object (class scala.Some, Some(BoundedPriorityQueue([Justin,19,3,undefined,undefined])))
StackTrace: jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:129)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:129)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by billreed63** [comment]
The code example above is missing a couple lines of code

```
var jsc = new SparkContext("local[*]", "foo");
var sqlContext = new SQLContext(jsc);
var rdd1 = jsc.textFile("/Users/billreed/eclairjs_dev/eclairjs-node/test/data/people.txt");
var sqlStructField1 = DataTypes.createStructField("name", org.apache.spark.sql.types.DataTypes.StringType, true);
var sqlStructField2 = DataTypes.createStructField("age", org.apache.spark.sql.types.DataTypes.IntegerType, true);
var sqlStructField3 = DataTypes.createStructField("expense", org.apache.spark.sql.types.DataTypes.IntegerType, true);
var sqlStructField4 = DataTypes.createStructField("hasjob", org.apache.spark.sql.types.DataTypes.BooleanType, true); // <<< missing
var sqlStructField5 = DataTypes.createStructField("isold", org.apache.spark.sql.types.DataTypes.BooleanType, true); // <<< missing

var rdd2 = rdd1.map(function (line) {
    var parts = line.split(",");
    return person = {
      name: parts[0],
      age: parseInt(parts[1].trim()),
      expense: parseInt(parts[2].trim()),
      hasJob: parts[3].trim() == "true" ? true : false, // <<< missing
      isOld: parts[4].trim() == "true" ? true : false // <<< missing
    };
  });
var sqlStructType1 = DataTypes.createStructType([sqlStructField1,sqlStructField2,sqlStructField3,sqlStructField4,sqlStructField5]);
var rdd3 = rdd2.map(function (person){
    return RowFactory.create([person.name, person.age, person.expense, person.hasJob, person.isOld]);
  });
var dataFrame1 = sqlContext.createDataFrame(rdd3, sqlStructType1);

var column1 = dataFrame1.col("age");
var column2 = column1.asc();
var dataFrame2 = dataFrame1.sort(column2);
print(JSON.stringify(dataFrame2.take(10)));
```

When I add the missing line of code the example works for me.

**Comment by doronrosenberg** [comment]
Yeah my bad, it was a local save state issue.
