### ISSUE TITLE
create wiki page for examples

### ISSUE THREAD

**Issue by pberkland** [EclairJS/eclairjs-nashorn#79]
create a wiki page that indexes the examples.   make sure that each example has the appropriate comments that show the user how to run.

**Comment by david-f** [comment]
Created https://github.com/EclairJS/eclairjs-node/wiki/EclairJS-Spark-Examples, which provides a 3-way index of examples that are in eclairjs-node, eclairjs-nashorn, and Apache. This will need occasional updating.
